FROM node:lts-bullseye-slim

# Create app directory
WORKDIR /app

COPY ./dist ./dist
COPY ./package*.json ./

RUN apt-get -qy update && apt-get -qy install openssl
RUN npm i graphql-fields
RUN npm install --production

EXPOSE 4000
CMD [ "node", "dist/index.js" ]